/* AUTO-GENERATED FILE. DO NOT EDIT MANUALLY. */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Endpoint */
        get: operations["health_endpoint_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drugs/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Suggest Drugs */
        get: operations["suggest_drugs_api_drugs_suggest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drugs/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Drug */
        post: operations["resolve_drug_api_drugs_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Analysis */
        post: operations["run_analysis_api_analysis_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis Result */
        get: operations["get_analysis_result_api_analysis__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{analysis_id}/share": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Share Analysis */
        post: operations["share_analysis_api_analysis__analysis_id__share_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/share/{share_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Share */
        get: operations["get_share_api_share__share_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analytics Event */
        post: operations["analytics_event_api_analytics_event_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{analysis_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Analysis Csv */
        get: operations["export_analysis_csv_api_analysis__analysis_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/{analysis_id}/export.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Analysis Json */
        get: operations["export_analysis_json_api_analysis__analysis_id__export_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compare/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare */
        post: operations["compare_api_compare_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisFlags */
        AnalysisFlags: {
            /**
             * Direction Unknown
             * @default false
             */
            direction_unknown: boolean;
            /**
             * Limited Data
             * @default false
             */
            limited_data: boolean;
            /**
             * Partial Mapping
             * @default false
             */
            partial_mapping: boolean;
            /**
             * High Variability
             * @default false
             */
            high_variability: boolean;
        };
        /** AnalysisParams */
        AnalysisParams: {
            /**
             * Pchembl Threshold
             * @default 5
             */
            pchembl_threshold: number;
            /**
             * Min Assays
             * @default 2
             */
            min_assays: number;
            /**
             * Include Low Confidence
             * @default false
             */
            include_low_confidence: boolean;
            /**
             * Top Pathways
             * @default 20
             */
            top_pathways: number;
        };
        /** AnalysisResult */
        AnalysisResult: {
            /** Analysis Id */
            analysis_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Drug Name */
            drug_name: string;
            /** Canonical Drug Id */
            canonical_drug_id: string;
            params: components["schemas"]["AnalysisParams"];
            resolution: components["schemas"]["DrugResolution"];
            /** Targets */
            targets: components["schemas"]["TargetHit"][];
            /** Pathways */
            pathways: components["schemas"]["PathwayScore"][];
            graph: components["schemas"]["AssociationGraph"];
            /** Source Versions */
            source_versions: {
                [key: string]: string;
            };
            /** Version Snapshot */
            version_snapshot?: {
                [key: string]: string;
            };
            analysis_flags?: components["schemas"]["AnalysisFlags"];
            /** Export Manifest */
            export_manifest?: {
                [key: string]: unknown;
            };
            /** Degraded Messages */
            degraded_messages?: string[];
            /** Attribution */
            attribution: string;
        };
        /** AnalysisRunRequest */
        AnalysisRunRequest: {
            /** Drug Name */
            drug_name: string;
            params?: components["schemas"]["AnalysisParams"];
            /**
             * Do Not Log
             * @default false
             */
            do_not_log: boolean;
            /** Resolution Choice */
            resolution_choice?: string | null;
        };
        /** AnalyticsEventRequest */
        AnalyticsEventRequest: {
            /** Event Name */
            event_name: string;
            /** Page Path */
            page_path: string;
        };
        /** ApiDependencyHealth */
        ApiDependencyHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "up" | "down";
            /** Latency Ms */
            latency_ms?: number | null;
            /** Error */
            error?: string | null;
        };
        /** ApiHealthStatus */
        ApiHealthStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "healthy" | "degraded" | "down";
            /** Apis */
            apis: {
                [key: string]: components["schemas"]["ApiDependencyHealth"];
            };
            /** Cache Hit Rate */
            cache_hit_rate: number;
            /** Etl Last Run */
            etl_last_run?: string | null;
        };
        /** AssociationGraph */
        AssociationGraph: {
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
        };
        /** CompareMetrics */
        CompareMetrics: {
            /** Target Jaccard */
            target_jaccard: number;
            /** Pathway Cosine Similarity */
            pathway_cosine_similarity: number;
            /** Shared Pathway Count */
            shared_pathway_count: number;
            /** Unique Pathway Count A */
            unique_pathway_count_a: number;
            /** Unique Pathway Count B */
            unique_pathway_count_b: number;
        };
        /** CompareResult */
        CompareResult: {
            analysis_a: components["schemas"]["AnalysisResult"];
            analysis_b: components["schemas"]["AnalysisResult"];
            /** Rows */
            rows: components["schemas"]["PathwayComparisonRow"][];
            metrics: components["schemas"]["CompareMetrics"];
        };
        /** CompareRunRequest */
        CompareRunRequest: {
            /** Drug A */
            drug_a: string;
            /** Drug B */
            drug_b: string;
            params?: components["schemas"]["AnalysisParams"];
        };
        /** DrugResolution */
        DrugResolution: {
            /** Query */
            query: string;
            /** Display Name */
            display_name: string;
            /** Chembl Parent Id */
            chembl_parent_id: string;
            /** Canonical Inchikey */
            canonical_inchikey: string;
            /** Pubchem Cid */
            pubchem_cid?: string | null;
            /** Structure Smiles */
            structure_smiles?: string | null;
            /** Synonyms */
            synonyms?: string[];
            /** Clinical Phase */
            clinical_phase?: number | null;
            /** Mechanism Of Action */
            mechanism_of_action?: string | null;
        };
        /** DrugResolutionCandidate */
        DrugResolutionCandidate: {
            /** Chembl Parent Id */
            chembl_parent_id: string;
            /** Display Name */
            display_name: string;
            /** Canonical Inchikey */
            canonical_inchikey: string;
            /** Match Reasons */
            match_reasons?: string[];
        };
        /** DrugResolveRequest */
        DrugResolveRequest: {
            /** Query */
            query: string;
            /** Resolution Choice */
            resolution_choice?: string | null;
        };
        /** DrugResolveResponse */
        DrugResolveResponse: {
            /** Query */
            query: string;
            /**
             * Status
             * @enum {string}
             */
            status: "resolved" | "ambiguous" | "not_found";
            resolution?: components["schemas"]["DrugResolution"] | null;
            /** Candidates */
            candidates?: components["schemas"]["DrugResolutionCandidate"][];
        };
        /** DrugSuggestItem */
        DrugSuggestItem: {
            /** Display Name */
            display_name: string;
            /** Chembl Id */
            chembl_id?: string | null;
        };
        /** DrugSuggestResponse */
        DrugSuggestResponse: {
            /** Query */
            query: string;
            /** Suggestions */
            suggestions: components["schemas"]["DrugSuggestItem"][];
        };
        /** ExportMetadata */
        ExportMetadata: {
            /** Analysis Id */
            analysis_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            params: components["schemas"]["AnalysisParams"];
            /** Attribution */
            attribution: string;
            /** Source Versions */
            source_versions?: {
                [key: string]: string;
            };
            /** Version Snapshot */
            version_snapshot?: {
                [key: string]: string;
            };
            analysis_flags?: components["schemas"]["AnalysisFlags"];
            /** Export Manifest */
            export_manifest?: {
                [key: string]: unknown;
            };
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "drug_target" | "target_pathway";
            /** Weight */
            weight: number;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "drug" | "target" | "pathway";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JsonExportResponse */
        JsonExportResponse: {
            metadata: components["schemas"]["ExportMetadata"];
            analysis: components["schemas"]["AnalysisResult"];
        };
        /** PathwayComparisonRow */
        PathwayComparisonRow: {
            /** Pathway Id */
            pathway_id: string;
            /** Pathway Name */
            pathway_name: string;
            /** Score A */
            score_a?: number | null;
            /** Score B */
            score_b?: number | null;
            /** Delta */
            delta?: number | null;
            /** Shared */
            shared: boolean;
        };
        /** PathwayScore */
        PathwayScore: {
            /** Pathway Id */
            pathway_id: string;
            /** Pathway Name */
            pathway_name: string;
            /** Depth */
            depth: number;
            /** Pathway Size */
            pathway_size: number;
            /** Targets Hit */
            targets_hit: number;
            /** Median Pchembl */
            median_pchembl: number;
            /** Score */
            score: number;
            /** Target Ids */
            target_ids: string[];
            /** Reactome Url */
            reactome_url: string;
            /** Ancestor Pathway Ids */
            ancestor_pathway_ids?: string[];
            /**
             * Coverage Ratio
             * @default 0
             */
            coverage_ratio: number;
        };
        /** ShareResponse */
        ShareResponse: {
            /** Share Id */
            share_id: string;
            /** Analysis Id */
            analysis_id: string;
            /** Public Url */
            public_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TargetHit */
        TargetHit: {
            /** Target Chembl Id */
            target_chembl_id: string;
            /** Target Name */
            target_name: string;
            /** Gene Symbol */
            gene_symbol?: string | null;
            /** Uniprot Id */
            uniprot_id?: string | null;
            /**
             * Action Type
             * @default UNKNOWN
             */
            action_type: string;
            /** Median Pchembl */
            median_pchembl: number;
            /** Assay Count */
            assay_count: number;
            /** Confidence Score */
            confidence_score?: number | null;
            /**
             * Confidence Tier
             * @enum {string}
             */
            confidence_tier: "high" | "medium" | "low";
            /** Low Confidence */
            low_confidence: boolean;
            /** Source Assay Ids */
            source_assay_ids?: string[];
            /** Pchembl Min */
            pchembl_min?: number | null;
            /** Pchembl Max */
            pchembl_max?: number | null;
            /** Pchembl Iqr */
            pchembl_iqr?: number | null;
            /** Confidence Reasons */
            confidence_reasons?: string[];
            /**
             * Mapping Status
             * @default mapped
             * @enum {string}
             */
            mapping_status: "mapped" | "partial" | "unmapped";
            /** Mapping Notes */
            mapping_notes?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_endpoint_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiHealthStatus"];
                };
            };
        };
    };
    suggest_drugs_api_drugs_suggest_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugSuggestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_drug_api_drugs_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DrugResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DrugResolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_analysis_api_analysis_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_result_api_analysis__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    share_analysis_api_analysis__analysis_id__share_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_share_api_share__share_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                share_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analytics_event_api_analytics_event_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyticsEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_analysis_csv_api_analysis__analysis_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_analysis_json_api_analysis__analysis_id__export_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_compare_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
