"""Bundled DILIrank dataset — well-characterised drugs from the FDA DILIrank publication.

No public API exists for DILIrank, so the reference data is embedded here
(same pattern as ``_DEFAULT_TOXICITY_GENE_SETS`` in ``etl/phase3_ingest.py``).

Source: FDA DILIrank — Chen M et al., Drug Discovery Today, 2016.
https://www.fda.gov/science-research/liver-toxicity-knowledge-base-ltkb/drug-induced-liver-injury-rank-dilirank-dataset
"""

from __future__ import annotations

_SOURCE_URL = (
    "https://www.fda.gov/science-research/liver-toxicity-knowledge-base-ltkb/"
    "drug-induced-liver-injury-rank-dilirank-dataset"
)

DILIRANK_ENTRIES: list[dict] = [
    # ---- Most-DILI-concern ----
    {"drug_name_norm": "acetaminophen", "drug_name_original": "Acetaminophen", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "isoniazid", "drug_name_original": "Isoniazid", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "valproic acid", "drug_name_original": "Valproic Acid", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "amiodarone", "drug_name_original": "Amiodarone", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "methotrexate", "drug_name_original": "Methotrexate", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "diclofenac", "drug_name_original": "Diclofenac", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ketoconazole", "drug_name_original": "Ketoconazole", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "nitrofurantoin", "drug_name_original": "Nitrofurantoin", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "phenytoin", "drug_name_original": "Phenytoin", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "carbamazepine", "drug_name_original": "Carbamazepine", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "chlorpromazine", "drug_name_original": "Chlorpromazine", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "flucloxacillin", "drug_name_original": "Flucloxacillin", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "halothane", "drug_name_original": "Halothane", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ibuprofen", "drug_name_original": "Ibuprofen", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "sulindac", "drug_name_original": "Sulindac", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "erythromycin", "drug_name_original": "Erythromycin", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "naproxen", "drug_name_original": "Naproxen", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "labetalol", "drug_name_original": "Labetalol", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "methyldopa", "drug_name_original": "Methyldopa", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "nefazodone", "drug_name_original": "Nefazodone", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "dantrolene", "drug_name_original": "Dantrolene", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "troglitazone", "drug_name_original": "Troglitazone", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "trovafloxacin", "drug_name_original": "Trovafloxacin", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "nimesulide", "drug_name_original": "Nimesulide", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "bromfenac", "drug_name_original": "Bromfenac", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "tolcapone", "drug_name_original": "Tolcapone", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "felbamate", "drug_name_original": "Felbamate", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "flutamide", "drug_name_original": "Flutamide", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "tamoxifen", "drug_name_original": "Tamoxifen", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "pyrazinamide", "drug_name_original": "Pyrazinamide", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "rifampin", "drug_name_original": "Rifampin", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "tetracycline", "drug_name_original": "Tetracycline", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "azathioprine", "drug_name_original": "Azathioprine", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cyclophosphamide", "drug_name_original": "Cyclophosphamide", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "dapsone", "drug_name_original": "Dapsone", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "disulfiram", "drug_name_original": "Disulfiram", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "oxyphenisatin", "drug_name_original": "Oxyphenisatin", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ticlopidine", "drug_name_original": "Ticlopidine", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "leflunomide", "drug_name_original": "Leflunomide", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "bosentan", "drug_name_original": "Bosentan", "dili_category": "Most-DILI-concern", "source_url": _SOURCE_URL},
    # ---- Less-DILI-concern ----
    {"drug_name_norm": "atorvastatin", "drug_name_original": "Atorvastatin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "simvastatin", "drug_name_original": "Simvastatin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "rosuvastatin", "drug_name_original": "Rosuvastatin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "lovastatin", "drug_name_original": "Lovastatin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "pravastatin", "drug_name_original": "Pravastatin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "fluvastatin", "drug_name_original": "Fluvastatin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ciprofloxacin", "drug_name_original": "Ciprofloxacin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "levofloxacin", "drug_name_original": "Levofloxacin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "moxifloxacin", "drug_name_original": "Moxifloxacin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "amoxicillin", "drug_name_original": "Amoxicillin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "azithromycin", "drug_name_original": "Azithromycin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "clarithromycin", "drug_name_original": "Clarithromycin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "fluconazole", "drug_name_original": "Fluconazole", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "itraconazole", "drug_name_original": "Itraconazole", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "terbinafine", "drug_name_original": "Terbinafine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "omeprazole", "drug_name_original": "Omeprazole", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "lansoprazole", "drug_name_original": "Lansoprazole", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "pantoprazole", "drug_name_original": "Pantoprazole", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ranitidine", "drug_name_original": "Ranitidine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cimetidine", "drug_name_original": "Cimetidine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "celecoxib", "drug_name_original": "Celecoxib", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "piroxicam", "drug_name_original": "Piroxicam", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "indomethacin", "drug_name_original": "Indomethacin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "meloxicam", "drug_name_original": "Meloxicam", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "duloxetine", "drug_name_original": "Duloxetine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "fluoxetine", "drug_name_original": "Fluoxetine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "paroxetine", "drug_name_original": "Paroxetine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "sertraline", "drug_name_original": "Sertraline", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "venlafaxine", "drug_name_original": "Venlafaxine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "trazodone", "drug_name_original": "Trazodone", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "buspirone", "drug_name_original": "Buspirone", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "risperidone", "drug_name_original": "Risperidone", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "olanzapine", "drug_name_original": "Olanzapine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "quetiapine", "drug_name_original": "Quetiapine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "clozapine", "drug_name_original": "Clozapine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "lamotrigine", "drug_name_original": "Lamotrigine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "topiramate", "drug_name_original": "Topiramate", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "gabapentin", "drug_name_original": "Gabapentin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "oxcarbazepine", "drug_name_original": "Oxcarbazepine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "pioglitazone", "drug_name_original": "Pioglitazone", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "rosiglitazone", "drug_name_original": "Rosiglitazone", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "metformin", "drug_name_original": "Metformin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "glyburide", "drug_name_original": "Glyburide", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "acarbose", "drug_name_original": "Acarbose", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "losartan", "drug_name_original": "Losartan", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "irbesartan", "drug_name_original": "Irbesartan", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "lisinopril", "drug_name_original": "Lisinopril", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "enalapril", "drug_name_original": "Enalapril", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "captopril", "drug_name_original": "Captopril", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "diltiazem", "drug_name_original": "Diltiazem", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "verapamil", "drug_name_original": "Verapamil", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "nifedipine", "drug_name_original": "Nifedipine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "amlodipine", "drug_name_original": "Amlodipine", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "propranolol", "drug_name_original": "Propranolol", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "atenolol", "drug_name_original": "Atenolol", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "warfarin", "drug_name_original": "Warfarin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "clopidogrel", "drug_name_original": "Clopidogrel", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "allopurinol", "drug_name_original": "Allopurinol", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "doxycycline", "drug_name_original": "Doxycycline", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "minocycline", "drug_name_original": "Minocycline", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "trimethoprim", "drug_name_original": "Trimethoprim", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "sulfamethoxazole", "drug_name_original": "Sulfamethoxazole", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "metronidazole", "drug_name_original": "Metronidazole", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "amoxicillin-clavulanate", "drug_name_original": "Amoxicillin-clavulanate", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cephalexin", "drug_name_original": "Cephalexin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "clindamycin", "drug_name_original": "Clindamycin", "dili_category": "Less-DILI-concern", "source_url": _SOURCE_URL},
    # ---- No-DILI-concern ----
    {"drug_name_norm": "aspirin", "drug_name_original": "Aspirin", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "caffeine", "drug_name_original": "Caffeine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "diphenhydramine", "drug_name_original": "Diphenhydramine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "loratadine", "drug_name_original": "Loratadine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cetirizine", "drug_name_original": "Cetirizine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "fexofenadine", "drug_name_original": "Fexofenadine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "pseudoephedrine", "drug_name_original": "Pseudoephedrine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "guaifenesin", "drug_name_original": "Guaifenesin", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ranitidine bismuth citrate", "drug_name_original": "Ranitidine Bismuth Citrate", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "famotidine", "drug_name_original": "Famotidine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "sucralfate", "drug_name_original": "Sucralfate", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "loperamide", "drug_name_original": "Loperamide", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "docusate", "drug_name_original": "Docusate", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "bisacodyl", "drug_name_original": "Bisacodyl", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "calcium carbonate", "drug_name_original": "Calcium Carbonate", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "magnesium hydroxide", "drug_name_original": "Magnesium Hydroxide", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ferrous sulfate", "drug_name_original": "Ferrous Sulfate", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "multivitamin", "drug_name_original": "Multivitamin", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "folic acid", "drug_name_original": "Folic Acid", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "thiamine", "drug_name_original": "Thiamine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "pyridoxine", "drug_name_original": "Pyridoxine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cyanocobalamin", "drug_name_original": "Cyanocobalamin", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ascorbic acid", "drug_name_original": "Ascorbic Acid", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cholecalciferol", "drug_name_original": "Cholecalciferol", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "hydrochlorothiazide", "drug_name_original": "Hydrochlorothiazide", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "furosemide", "drug_name_original": "Furosemide", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "spironolactone", "drug_name_original": "Spironolactone", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "metoprolol", "drug_name_original": "Metoprolol", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "levothyroxine", "drug_name_original": "Levothyroxine", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "insulin", "drug_name_original": "Insulin", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "albuterol", "drug_name_original": "Albuterol", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "montelukast", "drug_name_original": "Montelukast", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "fluticasone", "drug_name_original": "Fluticasone", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "prednisone", "drug_name_original": "Prednisone", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "prednisolone", "drug_name_original": "Prednisolone", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "dexamethasone", "drug_name_original": "Dexamethasone", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    {"drug_name_norm": "hydrocortisone", "drug_name_original": "Hydrocortisone", "dili_category": "No-DILI-concern", "source_url": _SOURCE_URL},
    # ---- Ambiguous DILI-concern ----
    {"drug_name_norm": "acetylsalicylic acid", "drug_name_original": "Acetylsalicylic Acid", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "rifabutin", "drug_name_original": "Rifabutin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ethambutol", "drug_name_original": "Ethambutol", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "norfloxacin", "drug_name_original": "Norfloxacin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "gatifloxacin", "drug_name_original": "Gatifloxacin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cefazolin", "drug_name_original": "Cefazolin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ceftriaxone", "drug_name_original": "Ceftriaxone", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ampicillin", "drug_name_original": "Ampicillin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "piperacillin", "drug_name_original": "Piperacillin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "vancomycin", "drug_name_original": "Vancomycin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "gentamicin", "drug_name_original": "Gentamicin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "amikacin", "drug_name_original": "Amikacin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "clotrimazole", "drug_name_original": "Clotrimazole", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "nystatin", "drug_name_original": "Nystatin", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "acyclovir", "drug_name_original": "Acyclovir", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "oseltamivir", "drug_name_original": "Oseltamivir", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "zidovudine", "drug_name_original": "Zidovudine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ritonavir", "drug_name_original": "Ritonavir", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "efavirenz", "drug_name_original": "Efavirenz", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "nevirapine", "drug_name_original": "Nevirapine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "chloroquine", "drug_name_original": "Chloroquine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "hydroxychloroquine", "drug_name_original": "Hydroxychloroquine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "mefloquine", "drug_name_original": "Mefloquine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "quinine", "drug_name_original": "Quinine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "sumatriptan", "drug_name_original": "Sumatriptan", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "ergotamine", "drug_name_original": "Ergotamine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "cyclobenzaprine", "drug_name_original": "Cyclobenzaprine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "baclofen", "drug_name_original": "Baclofen", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "methocarbamol", "drug_name_original": "Methocarbamol", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "colchicine", "drug_name_original": "Colchicine", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "probenecid", "drug_name_original": "Probenecid", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
    {"drug_name_norm": "febuxostat", "drug_name_original": "Febuxostat", "dili_category": "Ambiguous", "source_url": _SOURCE_URL},
]
